# Generated by Django 5.0.3 on 2024-03-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_created_at_user_updated_at_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                    ("scheduling", "Scheduling"),
                    ("scheduled", "Scheduled"),
                ],
                default="in_progress",
                max_length=50,
            ),
        ),
    ]
